- name: read vars
  include_vars: vars/{{ arch }}.yml

- name: create base path
  set_fact:
    source: "/usr/{{ arch }}-w64-mingw32/sys-root/mingw"
    target: "{{ ansible_user_dir }}/{{ arch }}/"
    target_file: "{{ ansible_user_dir }}/sword-utils-{{ \
                  sword_version }}-{{ arch }}"

- name: create target build directory
  file:
    dest: "{{ target }}/{{ item }}"
    state: directory
  with_items: "{{ builds }}"

- name: copy in non-strip files
  copy:
    src: "{{ source }}/bin/{{ item }}"
    dest: "{{ target }}/debug"
    remote_src: true
  with_items: "{{ copy_files + files + debug_files }}"

- name: copy in debug files
  copy:
    src: "{{ source }}/bin/{{ item }}.debug"
    dest: "{{ target }}/debug"
    remote_src: true
  with_items: "{{ files }}"

- name: strip files for release
  command: >-
    strip "{{ source }}/bin/{{ item }}" -o "{{ target }}/release/{{ item }}"
  args:
    creates: "{{ target }}/release/{{ item }}"
  with_items: "{{ files }}"

- name: copy-only files for release
  copy:
    src: "{{ source }}/bin/{{ item }}"
    dest: "{{ target }}/release"
    remote_src: true
  with_items: "{{ copy_files }}"

- name: create archives
  shell: zip "{{ target_file }}-{{ item }}.zip" *
  args:
    chdir: "{{ target }}/{{ item }}"
  with_items: "{{ builds }}"
  changed_when: false

- name: fetch results
  fetch:
    src: "{{ target_file }}-{{ item }}.zip"
    dest: "{{ download_dest }}"
    flat: true
  with_items: "{{ builds }}"
  changed_when: false
