- name: install package
  become: true
  package:
    name: "{{ packages }}"
    state: present
    enablerepo: fedora-debuginfo,updates-debuginfo,updates-testing,updates-testing-debuginfo
    disablerepo: fedora-modular,updates-modular

- name: fetch version
  command: rpm -qv --qf '%{VERSION}' mingw32-sword
  args:
    warn: false
  register: rpm_version
  changed_when: false
  tags:
    - skip_ansible_lint

- name: register version
  set_fact:
    sword_version: "{{ rpm_version.stdout.strip() }}"

- name: do the thing
  include_tasks: arch.yml
  vars:
    arch: "{{ outer_item }}"
  with_items:
    - i686
    - x86_64
  loop_control:
    loop_var: outer_item
