dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: fedora:latest
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      stdout_callback: yaml
      force_color: true
verifier:
  name: testinfra
  lint:
    name: flake8
