name: Make zips

"on":
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-ansible
          tox
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./*.zip
          allowUpdates: true
          name: Release ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
